server:
  port: ${SCRIBBLE_AUTH_SERVICE_PORT}
spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SCRIBBLE_AUTH_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

aws:
  cognito:
    connectionTimeout: '2000'
    userPoolId: ${SCRIBBLE_AUTH_AWS_COGNITO_USERPOOL_ID}
    jwk: ${SCRIBBLE_AUTH_AWS_COGNITO_JWK}
    clientId: ${SCRIBBLE_AUTH_AWS_COGNITO_CLIENT_ID}
    region: ${SCRIBBLE_AUTH_AWS_COGNITO_REGION}
    readTimeout: '2000'
  access-key: ${SCRIBBLE_AUTH_AWS_ACCESS_KEY}
  access-secret: ${SCRIBBLE_AUTH_AWS_SECRET_KEY}
  default-region: ${SCRIBBLE_AUTH_AWS_DEFAULT_REGION}


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            security:
              servlet:
                UserDetailsServiceAutoConfiguration: 'OFF'

app:
  cors:
    allowedOrigins: http://localhost:4200 # Comma separated list of allowed origins

cookieDomain: ${COOKIE_DOMAIN}




