version: "3.8"
services:
    scribble-app:
        platform: linux/amd64
        build:
            context: ./scribble-app
        ports:
            - "4200:80" # because angular assets are served through nginx and default port for nginx is 80
        container_name: scribble-app
        depends_on:
            [api-gateway, auth-service, note-service]

    api-gateway:
        restart: always
        image: nginx:latest
        container_name: api-gateway
        volumes:
            - "./api-gateway/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "9000:80"          

    auth-service:
        platform: linux/amd64
        build:
            context: ./auth-service
        ports:
            - "9001:9001"
        container_name: auth-service
        depends_on:
            [api-gateway]
        environment:
            - SCRIBBLE_AUTH_SERVICE_PORT=${SCRIBBLE_AUTH_SERVICE_PORT}
            - SCRIBBLE_AUTH_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=${SCRIBBLE_AUTH_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
            - SCRIBBLE_AUTH_AWS_COGNITO_USERPOOL_ID=${SCRIBBLE_AUTH_AWS_COGNITO_USERPOOL_ID}
            - SCRIBBLE_AUTH_AWS_COGNITO_JWK=${SCRIBBLE_AUTH_AWS_COGNITO_JWK}
            - SCRIBBLE_AUTH_AWS_COGNITO_CLIENT_ID=${SCRIBBLE_AUTH_AWS_COGNITO_CLIENT_ID}
            - SCRIBBLE_AUTH_AWS_COGNITO_REGION=${SCRIBBLE_AUTH_AWS_COGNITO_REGION}
            - SCRIBBLE_AUTH_AWS_ACCESS_KEY=${SCRIBBLE_AUTH_AWS_ACCESS_KEY}
            - SCRIBBLE_AUTH_AWS_SECRET_KEY=${SCRIBBLE_AUTH_AWS_SECRET_KEY}
            - SCRIBBLE_AUTH_AWS_DEFAULT_REGION=${SCRIBBLE_AUTH_AWS_DEFAULT_REGION}
            - EUREKA_CLIENT_DEFAULTZONE=${EUREKA_CLIENT_DEFAULTZONE}
            - COOKIE_DOMAIN=${COOKIE_DOMAIN}
       

    note-service:
        platform: linux/amd64
        build:
            context: ./note-service
        ports:
            - "9002:9002"
        container_name: note-service
        depends_on:
            [api-gateway, auth-service]
        environment:
            - SCRIBBLE_NOTE_SERVICE_PORT=${SCRIBBLE_NOTE_SERVICE_PORT}
            - SCRIBBLE_AUTH_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=${SCRIBBLE_AUTH_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
            - SCRIBBLE_DB_ENDPOINT=${SCRIBBLE_DB_ENDPOINT}
            - SCRIBBLE_NOTESDB_USERNAME=${SCRIBBLE_NOTESDB_USERNAME}
            - SCRIBBLE_NOTESDB_PASSWORD=${SCRIBBLE_NOTESDB_PASSWORD}
            - SCRIBBLE_AUTH_AWS_COGNITO_USERPOOL_ID=${SCRIBBLE_AUTH_AWS_COGNITO_USERPOOL_ID}
            - SCRIBBLE_AUTH_AWS_COGNITO_JWK=${SCRIBBLE_AUTH_AWS_COGNITO_JWK}
            - SCRIBBLE_AUTH_AWS_COGNITO_CLIENT_ID=${SCRIBBLE_AUTH_AWS_COGNITO_CLIENT_ID}
            - SCRIBBLE_AUTH_AWS_COGNITO_REGION=${SCRIBBLE_AUTH_AWS_COGNITO_REGION}
            - SCRIBBLE_AUTH_AWS_ACCESS_KEY=${SCRIBBLE_AUTH_AWS_ACCESS_KEY}
            - SCRIBBLE_AUTH_AWS_SECRET_KEY=${SCRIBBLE_AUTH_AWS_SECRET_KEY}
            - SCRIBBLE_AUTH_AWS_DEFAULT_REGION=${SCRIBBLE_AUTH_AWS_DEFAULT_REGION}
            - EUREKA_SERVICE_REGISTRATION=${EUREKA_SERVICE_REGISTRATION}
            - EUREKA_CLIENT_DEFAULTZONE=${EUREKA_CLIENT_DEFAULTZONE}

    # notesdb:
    #     container_name: scribble-notesdb
    #     image: postgres
    #     ports:
    #         - "5432:5432"
    #     environment:
    #         - POSTGRES_USER=postgres 
    #         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
    #         - POSTGRES_DB=notesdb 
    #     volumes:
    #         - ./postgres-data:/var/lib/postgresql/data
        