server:
    port: ${SCRIBBLE_NOTE_SERVICE_PORT}
spring:
    application:
        name: note-service
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${SCRIBBLE_AUTH_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
    jackson:
        default-property-inclusion: non_null # to NOT include any null values in the json response
        time-zone: UTC
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: 'false'


    datasource:
#        url: jdbc:postgresql://${LOCAL_DOCKER_VM_IP}:5432/notesdb
        url: ${SCRIBBLE_DB_ENDPOINT}
        driverClassName: org.postgresql.Driver
        platform: postgres
        username: ${SCRIBBLE_NOTESDB_USERNAME}
        password: ${SCRIBBLE_NOTESDB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
#                format_sql: 'true'
#        show-sql: 'true'

aws:
    cognito:
        connectionTimeout: '2000'
        userPoolId: ${SCRIBBLE_AUTH_AWS_COGNITO_USERPOOL_ID}
        jwk: ${SCRIBBLE_AUTH_AWS_COGNITO_JWK}
        clientId: ${SCRIBBLE_AUTH_AWS_COGNITO_CLIENT_ID}
        region: ${SCRIBBLE_AUTH_AWS_COGNITO_REGION}
        readTimeout: '2000'
    access-key: ${SCRIBBLE_AUTH_AWS_ACCESS_KEY}
    access-secret: ${SCRIBBLE_AUTH_AWS_SECRET_KEY}
    default-region: ${SCRIBBLE_AUTH_AWS_DEFAULT_REGION}


logging:
    level:
        org:
            springframework:
                boot:
                    autoconfigure:
                        security:
                            servlet:
                                UserDetailsServiceAutoConfiguration: 'OFF'
eureka:
    client:
        register-with-eureka: ${EUREKA_SERVICE_REGISTRATION}
        fetch-registry: ${EUREKA_SERVICE_REGISTRATION}
        service-url:
            defaultZone: ${EUREKA_CLIENT_DEFAULTZONE}
    instance:
        prefer-ip-address: true
