server:
    port: ${SCRIBBLE_NOTE_SERVICE_PORT}
spring:
    application:
        name: note-service
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
